# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Gather Ansible facts
  ansible.builtin.gather_facts:

- name: Include distribution vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Install distribution packages
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}/packages-install.yml"

- name: Setup lvi dependencies
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}/lvi-setup.yml"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install CMake 3.13.1
  ansible.builtin.unarchive:
    src: https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz
    dest: "{{ cmake_prefix }}"
    remote_src: yes
  retries: 10
  delay: 10
  register: result
  until: result is success

- name: Create CMake symbolic links
  ansible.builtin.file:
    src: "{{ cmake_prefix }}/cmake-3.13.1-Linux-x86_64/bin/{{ item }}"
    dest: "{{ cmake_prefix }}/bin/{{ item }}"
    force: yes
    state: link
  with_items:
    - ccmake
    - cmake
    - cpack
    - ctest
