# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.
#
# For documentation on the format of this file, see
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "3rdparty/openssl/openssl"
      - dependency-name: "snmalloc"
        update-types: ["version-update:semver-major"]
