# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- block:
  - name: Import Jenkins agent provision tasks
    ansible.builtin.import_role:
      name: common/jenkins
      tasks_from: agent-provision.yml
    delegate_to: localhost
  become: no

- name: Jenkins | Check if node_secret fact is defined
  ansible.builtin.fail:
    msg: "The node_secret fact is not defined!"
  when: node_secret is undefined

- name: Jenkins | Install Java JRE needed by Jenkins
  ansible.builtin.apt:
    name: openjdk-8-jre
    state: latest
    update_cache: yes
  retries: 10
  delay: 10
  register: result
  until: result is success

- name: Jenkins | Create the Jenkins group
  ansible.builtin.group:
    name: jenkins
    state: present

- name: Jenkins | Add the Jenkins user
  ansible.builtin.user:
    name: jenkins
    group: jenkins
    state: present

- name: Jenkins | Import Docker install tasks
  ansible.builtin.import_role:
    name: linux/docker
    tasks_from: stable-install.yml

- name: Jenkins | Add the Jenkins system user to the Docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker

- name: Jenkins | Make Jenkins JNLP slave directories
  ansible.builtin.file:
    path: "{{ jenkins_agent_root_dir }}"
    state: directory
    owner: jenkins
    group: jenkins

- name: Jenkins | Template Jenkins JNLP slave files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: jenkins-slave.service.j2, dest: /etc/systemd/system/jenkins-slave.service, mode: 755 }
    - { src: jenkins-slave.default.j2, dest: /etc/default/jenkins-slave, mode: 644 }

- name: Jenkins | Start Jenkins JNLP slave
  ansible.builtin.systemd:
    name: jenkins-slave
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Jenkins | Configure Git in target image to enable merge/rebase actions - email
  community.general.git_config:
    name: user.email
    scope: system
    value: '{{ ci_team_email }}'

- name: Jenkins | Configure Git in target image to enable merge/rebase actions - name
  community.general.git_config:
    name: user.name
    scope: system
    value: '{{ ci_team_name }}'
