# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Check for existing required binaries
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries }}"
  register: binary
  failed_when: not binary.stat.executable
