# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Include distribution release specific vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"

- name: Check for existing required files
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items: "{{ packages_validation_distribution_files }}"
  register: file
  failed_when: not file.stat.exists
