# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Gather Ansible facts
  ansible.builtin.gather_facts:

- name: Include distribution vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Include distribution release specific vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"

- name: Install the SGX packages
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}/sgx-packages-install.yml"
