# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Setup Docker
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}/stable-install.yml"
