# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Check for existing required executables and files
  ansible.windows.win_stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries }}"
  register: file
  failed_when: not file.stat.isreg
